apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: vf
spec:
  ports:
    - port: 80
  selector:
    app: vf
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app
  labels:
    app: vf
spec:
  selector:
    matchLabels:
      app: vf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vf
    spec:
      containers:
      - image: abual/vf:latest
        name: app
        env:
        - name: DB_CONNECTIONSTRING
          value: mysql-service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_password
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: port
        ports:
        - containerPort: 80
          name: app
